# Generated by Django 4.2.5 on 2023-10-06 06:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre_name', models.CharField(blank=True, max_length=30, unique=True, verbose_name='Жанр')),
            ],
            options={
                'verbose_name': 'Жанр',
                'verbose_name_plural': 'Жанры',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(blank=True, max_length=20, verbose_name='Тип')),
            ],
            options={
                'verbose_name': 'Тип',
                'verbose_name_plural': 'Типы',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Manga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_manga', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='title_manga')),
                ('slug_manga', models.SlugField(default='', max_length=100, unique=True, verbose_name='URL slug')),
                ('manga_year', models.DateField(blank=True, verbose_name='Year of Born')),
                ('manga_posted_date', models.DateField(auto_now_add=True, verbose_name='Created Date')),
                ('manga_synopsis', models.TextField(max_length=300, verbose_name='Краткое описание')),
                ('manga_image', models.ImageField(blank=True, default='', upload_to='media/images', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpeg', 'img'])], verbose_name='Icon for Manga')),
                ('genre_manga', models.ManyToManyField(related_name='genres', to='manga.genre', verbose_name='Genre Manga')),
                ('type_manga', models.ManyToManyField(related_name='types', to='manga.type', verbose_name='Type Manga')),
            ],
            options={
                'verbose_name': 'Manga',
                'verbose_name_plural': 'Manga',
                'ordering': ('slug_manga',),
            },
        ),
    ]
