# Generated by Django 4.2.5 on 2023-10-07 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manga',
            name='slug_manga',
            field=models.SlugField(blank=True, default='', max_length=100, unique=True, verbose_name='URL slug'),
        ),
    ]
