# Generated by Django 4.2.5 on 2023-10-07 16:55

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0002_alter_manga_slug_manga'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manga',
            name='slug_manga',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='title_manga', unique=True),
        ),
    ]
